# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from openapi_client.models.field_type import FieldType
from openapi_client.models.get_field_profile import GetFieldProfile
from openapi_client.models.page_get_field_profile import PageGetFieldProfile

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class FieldProfilesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_container_field_profiles_listing(
        self,
        id: Annotated[Optional[StrictInt], Field(description="The field profile `ID`")] = None,
        datastore: Annotated[Optional[StrictInt], Field(description="The datastore `ID`")] = None,
        containers: Annotated[Optional[List[StrictInt]], Field(description="The container `ID`")] = None,
        latest_only: Annotated[Optional[StrictBool], Field(description="If it's the latest field profile")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[GetFieldProfile]:
        """Get Container Field Profiles Listing

        Retrieves a list of field profiles values of the latest profiled Container.  Authorized Roles: Admin, Manager, Member

        :param id: The field profile `ID`
        :type id: int
        :param datastore: The datastore `ID`
        :type datastore: int
        :param containers: The container `ID`
        :type containers: List[int]
        :param latest_only: If it's the latest field profile
        :type latest_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_container_field_profiles_listing_serialize(
            id=id,
            datastore=datastore,
            containers=containers,
            latest_only=latest_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[GetFieldProfile]",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_container_field_profiles_listing_with_http_info(
        self,
        id: Annotated[Optional[StrictInt], Field(description="The field profile `ID`")] = None,
        datastore: Annotated[Optional[StrictInt], Field(description="The datastore `ID`")] = None,
        containers: Annotated[Optional[List[StrictInt]], Field(description="The container `ID`")] = None,
        latest_only: Annotated[Optional[StrictBool], Field(description="If it's the latest field profile")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[GetFieldProfile]]:
        """Get Container Field Profiles Listing

        Retrieves a list of field profiles values of the latest profiled Container.  Authorized Roles: Admin, Manager, Member

        :param id: The field profile `ID`
        :type id: int
        :param datastore: The datastore `ID`
        :type datastore: int
        :param containers: The container `ID`
        :type containers: List[int]
        :param latest_only: If it's the latest field profile
        :type latest_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_container_field_profiles_listing_serialize(
            id=id,
            datastore=datastore,
            containers=containers,
            latest_only=latest_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[GetFieldProfile]",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_container_field_profiles_listing_without_preload_content(
        self,
        id: Annotated[Optional[StrictInt], Field(description="The field profile `ID`")] = None,
        datastore: Annotated[Optional[StrictInt], Field(description="The datastore `ID`")] = None,
        containers: Annotated[Optional[List[StrictInt]], Field(description="The container `ID`")] = None,
        latest_only: Annotated[Optional[StrictBool], Field(description="If it's the latest field profile")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Container Field Profiles Listing

        Retrieves a list of field profiles values of the latest profiled Container.  Authorized Roles: Admin, Manager, Member

        :param id: The field profile `ID`
        :type id: int
        :param datastore: The datastore `ID`
        :type datastore: int
        :param containers: The container `ID`
        :type containers: List[int]
        :param latest_only: If it's the latest field profile
        :type latest_only: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_container_field_profiles_listing_serialize(
            id=id,
            datastore=datastore,
            containers=containers,
            latest_only=latest_only,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[GetFieldProfile]",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_container_field_profiles_listing_serialize(
        self,
        id,
        datastore,
        containers,
        latest_only,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'containers': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if id is not None:
            
            _query_params.append(('id', id))
            
        if datastore is not None:
            
            _query_params.append(('datastore', datastore))
            
        if containers is not None:
            
            _query_params.append(('containers', containers))
            
        if latest_only is not None:
            
            _query_params.append(('latest_only', latest_only))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'AsyncHTTPBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/field-profiles/listing',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_field_profile(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetFieldProfile:
        """Get Field Profile

          Authorized Roles: Admin, Manager, Member

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_field_profile_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_field_profile_with_http_info(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetFieldProfile]:
        """Get Field Profile

          Authorized Roles: Admin, Manager, Member

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_field_profile_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_field_profile_without_preload_content(
        self,
        id: StrictInt,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Field Profile

          Authorized Roles: Admin, Manager, Member

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_field_profile_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_field_profile_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'AsyncHTTPBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/field-profiles/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_fields_profiles(
        self,
        name: Optional[StrictStr] = None,
        type: Optional[List[FieldType]] = None,
        datastore: Optional[List[StrictInt]] = None,
        container: Optional[List[StrictInt]] = None,
        tag: Optional[List[StrictStr]] = None,
        sort_name: Optional[StrictStr] = None,
        sort_created: Optional[StrictStr] = None,
        sort_type: Optional[StrictStr] = None,
        sort_completeness: Optional[StrictStr] = None,
        sort_active_checks: Optional[StrictStr] = None,
        sort_active_anomalies: Optional[StrictStr] = None,
        sort_quality_score: Optional[StrictStr] = None,
        latest_only: Optional[StrictBool] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number")] = None,
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Page size")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PageGetFieldProfile:
        """Get Fields Profiles

        Returns a list of your Field Profiles by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  Authorized Roles: Admin, Manager, Member

        :param name:
        :type name: str
        :param type:
        :type type: List[FieldType]
        :param datastore:
        :type datastore: List[int]
        :param container:
        :type container: List[int]
        :param tag:
        :type tag: List[str]
        :param sort_name:
        :type sort_name: str
        :param sort_created:
        :type sort_created: str
        :param sort_type:
        :type sort_type: str
        :param sort_completeness:
        :type sort_completeness: str
        :param sort_active_checks:
        :type sort_active_checks: str
        :param sort_active_anomalies:
        :type sort_active_anomalies: str
        :param sort_quality_score:
        :type sort_quality_score: str
        :param latest_only:
        :type latest_only: bool
        :param page: Page number
        :type page: int
        :param size: Page size
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_fields_profiles_serialize(
            name=name,
            type=type,
            datastore=datastore,
            container=container,
            tag=tag,
            sort_name=sort_name,
            sort_created=sort_created,
            sort_type=sort_type,
            sort_completeness=sort_completeness,
            sort_active_checks=sort_active_checks,
            sort_active_anomalies=sort_active_anomalies,
            sort_quality_score=sort_quality_score,
            latest_only=latest_only,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageGetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_fields_profiles_with_http_info(
        self,
        name: Optional[StrictStr] = None,
        type: Optional[List[FieldType]] = None,
        datastore: Optional[List[StrictInt]] = None,
        container: Optional[List[StrictInt]] = None,
        tag: Optional[List[StrictStr]] = None,
        sort_name: Optional[StrictStr] = None,
        sort_created: Optional[StrictStr] = None,
        sort_type: Optional[StrictStr] = None,
        sort_completeness: Optional[StrictStr] = None,
        sort_active_checks: Optional[StrictStr] = None,
        sort_active_anomalies: Optional[StrictStr] = None,
        sort_quality_score: Optional[StrictStr] = None,
        latest_only: Optional[StrictBool] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number")] = None,
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Page size")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PageGetFieldProfile]:
        """Get Fields Profiles

        Returns a list of your Field Profiles by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  Authorized Roles: Admin, Manager, Member

        :param name:
        :type name: str
        :param type:
        :type type: List[FieldType]
        :param datastore:
        :type datastore: List[int]
        :param container:
        :type container: List[int]
        :param tag:
        :type tag: List[str]
        :param sort_name:
        :type sort_name: str
        :param sort_created:
        :type sort_created: str
        :param sort_type:
        :type sort_type: str
        :param sort_completeness:
        :type sort_completeness: str
        :param sort_active_checks:
        :type sort_active_checks: str
        :param sort_active_anomalies:
        :type sort_active_anomalies: str
        :param sort_quality_score:
        :type sort_quality_score: str
        :param latest_only:
        :type latest_only: bool
        :param page: Page number
        :type page: int
        :param size: Page size
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_fields_profiles_serialize(
            name=name,
            type=type,
            datastore=datastore,
            container=container,
            tag=tag,
            sort_name=sort_name,
            sort_created=sort_created,
            sort_type=sort_type,
            sort_completeness=sort_completeness,
            sort_active_checks=sort_active_checks,
            sort_active_anomalies=sort_active_anomalies,
            sort_quality_score=sort_quality_score,
            latest_only=latest_only,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageGetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_fields_profiles_without_preload_content(
        self,
        name: Optional[StrictStr] = None,
        type: Optional[List[FieldType]] = None,
        datastore: Optional[List[StrictInt]] = None,
        container: Optional[List[StrictInt]] = None,
        tag: Optional[List[StrictStr]] = None,
        sort_name: Optional[StrictStr] = None,
        sort_created: Optional[StrictStr] = None,
        sort_type: Optional[StrictStr] = None,
        sort_completeness: Optional[StrictStr] = None,
        sort_active_checks: Optional[StrictStr] = None,
        sort_active_anomalies: Optional[StrictStr] = None,
        sort_quality_score: Optional[StrictStr] = None,
        latest_only: Optional[StrictBool] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number")] = None,
        size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Page size")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Fields Profiles

        Returns a list of your Field Profiles by setting the values of the parameters passed. Any parameters not provided will be left unchanged.  Authorized Roles: Admin, Manager, Member

        :param name:
        :type name: str
        :param type:
        :type type: List[FieldType]
        :param datastore:
        :type datastore: List[int]
        :param container:
        :type container: List[int]
        :param tag:
        :type tag: List[str]
        :param sort_name:
        :type sort_name: str
        :param sort_created:
        :type sort_created: str
        :param sort_type:
        :type sort_type: str
        :param sort_completeness:
        :type sort_completeness: str
        :param sort_active_checks:
        :type sort_active_checks: str
        :param sort_active_anomalies:
        :type sort_active_anomalies: str
        :param sort_quality_score:
        :type sort_quality_score: str
        :param latest_only:
        :type latest_only: bool
        :param page: Page number
        :type page: int
        :param size: Page size
        :type size: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_fields_profiles_serialize(
            name=name,
            type=type,
            datastore=datastore,
            container=container,
            tag=tag,
            sort_name=sort_name,
            sort_created=sort_created,
            sort_type=sort_type,
            sort_completeness=sort_completeness,
            sort_active_checks=sort_active_checks,
            sort_active_anomalies=sort_active_anomalies,
            sort_quality_score=sort_quality_score,
            latest_only=latest_only,
            page=page,
            size=size,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PageGetFieldProfile",
            '400': None,
            '403': None,
            '404': None,
            '409': None,
            '415': None,
            '422': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_fields_profiles_serialize(
        self,
        name,
        type,
        datastore,
        container,
        tag,
        sort_name,
        sort_created,
        sort_type,
        sort_completeness,
        sort_active_checks,
        sort_active_anomalies,
        sort_quality_score,
        latest_only,
        page,
        size,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'type': 'multi',
            'datastore': 'multi',
            'container': 'multi',
            'tag': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if name is not None:
            
            _query_params.append(('name', name))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        if datastore is not None:
            
            _query_params.append(('datastore', datastore))
            
        if container is not None:
            
            _query_params.append(('container', container))
            
        if tag is not None:
            
            _query_params.append(('tag', tag))
            
        if sort_name is not None:
            
            _query_params.append(('sort_name', sort_name))
            
        if sort_created is not None:
            
            _query_params.append(('sort_created', sort_created))
            
        if sort_type is not None:
            
            _query_params.append(('sort_type', sort_type))
            
        if sort_completeness is not None:
            
            _query_params.append(('sort_completeness', sort_completeness))
            
        if sort_active_checks is not None:
            
            _query_params.append(('sort_active_checks', sort_active_checks))
            
        if sort_active_anomalies is not None:
            
            _query_params.append(('sort_active_anomalies', sort_active_anomalies))
            
        if sort_quality_score is not None:
            
            _query_params.append(('sort_quality_score', sort_quality_score))
            
        if latest_only is not None:
            
            _query_params.append(('latest_only', latest_only))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if size is not None:
            
            _query_params.append(('size', size))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'AsyncHTTPBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/field-profiles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


