# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from openapi_client.models.datastore_search import DatastoreSearch
from typing import Optional, Set
from typing_extensions import Self

class ContainerSearch(BaseModel):
    """
    ContainerSearch
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    container_type: StrictStr
    datastore: DatastoreSearch
    __properties: ClassVar[List[str]] = ["id", "name", "container_type", "datastore"]

    @field_validator('container_type')
    def container_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['table', 'file', 'computed_table', 'computed_file', 'computed_join']):
            raise ValueError("must be one of enum values ('table', 'file', 'computed_table', 'computed_file', 'computed_join')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContainerSearch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of datastore
        if self.datastore:
            _dict['datastore'] = self.datastore.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContainerSearch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "container_type": obj.get("container_type"),
            "datastore": DatastoreSearch.from_dict(obj["datastore"]) if obj.get("datastore") is not None else None
        })
        return _obj


