# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.container2 import Container2
from typing import Optional, Set
from typing_extensions import Self

class ContainerScanStub(BaseModel):
    """
    ContainerScanStub
    """ # noqa: E501
    created: datetime
    id: StrictInt
    container: Container2
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    records_processed: Optional[StrictInt] = None
    anomaly_count: StrictInt
    open_anomaly_count: StrictInt
    archived_anomaly_count: StrictInt
    result: StrictStr
    message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created", "id", "container", "start_time", "end_time", "records_processed", "anomaly_count", "open_anomaly_count", "archived_anomaly_count", "result", "message"]

    @field_validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'failure', 'aborted', 'running']):
            raise ValueError("must be one of enum values ('success', 'failure', 'aborted', 'running')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContainerScanStub from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of container
        if self.container:
            _dict['container'] = self.container.to_dict()
        # set to None if start_time (nullable) is None
        # and model_fields_set contains the field
        if self.start_time is None and "start_time" in self.model_fields_set:
            _dict['start_time'] = None

        # set to None if end_time (nullable) is None
        # and model_fields_set contains the field
        if self.end_time is None and "end_time" in self.model_fields_set:
            _dict['end_time'] = None

        # set to None if records_processed (nullable) is None
        # and model_fields_set contains the field
        if self.records_processed is None and "records_processed" in self.model_fields_set:
            _dict['records_processed'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContainerScanStub from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "id": obj.get("id"),
            "container": Container2.from_dict(obj["container"]) if obj.get("container") is not None else None,
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "records_processed": obj.get("records_processed"),
            "anomaly_count": obj.get("anomaly_count"),
            "open_anomaly_count": obj.get("open_anomaly_count"),
            "archived_anomaly_count": obj.get("archived_anomaly_count"),
            "result": obj.get("result"),
            "message": obj.get("message")
        })
        return _obj


