# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from swagger_client.models.quality_score import QualityScore
from typing import Optional, Set
from typing_extensions import Self

class ContainerMetrics(BaseModel):
    """
    ContainerMetrics
    """ # noqa: E501
    last_profiled: Optional[datetime] = None
    last_scanned: Optional[datetime] = None
    fields: Optional[StrictInt] = None
    records: Optional[StrictInt] = None
    completeness: Optional[Union[StrictFloat, StrictInt]] = None
    active_checks: Optional[StrictInt] = None
    important_checks: Optional[StrictInt] = None
    passing_checks: Optional[StrictInt] = None
    failing_checks: Optional[StrictInt] = None
    anomalies: Optional[StrictInt] = None
    active_anomalies: Optional[StrictInt] = None
    quality_score: Optional[QualityScore] = None
    __properties: ClassVar[List[str]] = ["last_profiled", "last_scanned", "fields", "records", "completeness", "active_checks", "important_checks", "passing_checks", "failing_checks", "anomalies", "active_anomalies", "quality_score"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContainerMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quality_score
        if self.quality_score:
            _dict['quality_score'] = self.quality_score.to_dict()
        # set to None if last_profiled (nullable) is None
        # and model_fields_set contains the field
        if self.last_profiled is None and "last_profiled" in self.model_fields_set:
            _dict['last_profiled'] = None

        # set to None if last_scanned (nullable) is None
        # and model_fields_set contains the field
        if self.last_scanned is None and "last_scanned" in self.model_fields_set:
            _dict['last_scanned'] = None

        # set to None if fields (nullable) is None
        # and model_fields_set contains the field
        if self.fields is None and "fields" in self.model_fields_set:
            _dict['fields'] = None

        # set to None if records (nullable) is None
        # and model_fields_set contains the field
        if self.records is None and "records" in self.model_fields_set:
            _dict['records'] = None

        # set to None if completeness (nullable) is None
        # and model_fields_set contains the field
        if self.completeness is None and "completeness" in self.model_fields_set:
            _dict['completeness'] = None

        # set to None if active_checks (nullable) is None
        # and model_fields_set contains the field
        if self.active_checks is None and "active_checks" in self.model_fields_set:
            _dict['active_checks'] = None

        # set to None if important_checks (nullable) is None
        # and model_fields_set contains the field
        if self.important_checks is None and "important_checks" in self.model_fields_set:
            _dict['important_checks'] = None

        # set to None if passing_checks (nullable) is None
        # and model_fields_set contains the field
        if self.passing_checks is None and "passing_checks" in self.model_fields_set:
            _dict['passing_checks'] = None

        # set to None if failing_checks (nullable) is None
        # and model_fields_set contains the field
        if self.failing_checks is None and "failing_checks" in self.model_fields_set:
            _dict['failing_checks'] = None

        # set to None if anomalies (nullable) is None
        # and model_fields_set contains the field
        if self.anomalies is None and "anomalies" in self.model_fields_set:
            _dict['anomalies'] = None

        # set to None if active_anomalies (nullable) is None
        # and model_fields_set contains the field
        if self.active_anomalies is None and "active_anomalies" in self.model_fields_set:
            _dict['active_anomalies'] = None

        # set to None if quality_score (nullable) is None
        # and model_fields_set contains the field
        if self.quality_score is None and "quality_score" in self.model_fields_set:
            _dict['quality_score'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContainerMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "last_profiled": obj.get("last_profiled"),
            "last_scanned": obj.get("last_scanned"),
            "fields": obj.get("fields"),
            "records": obj.get("records"),
            "completeness": obj.get("completeness"),
            "active_checks": obj.get("active_checks"),
            "important_checks": obj.get("important_checks"),
            "passing_checks": obj.get("passing_checks"),
            "failing_checks": obj.get("failing_checks"),
            "anomalies": obj.get("anomalies"),
            "active_anomalies": obj.get("active_anomalies"),
            "quality_score": QualityScore.from_dict(obj["quality_score"]) if obj.get("quality_score") is not None else None
        })
        return _obj


