# coding: utf-8

"""
    Surveillance Hub

    Qualytics API  # noqa: E501

    OpenAPI spec version: 5ca80d8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateJdbcCatalogDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'version': 'str',
        'driver_name': 'str',
        'driver_version': 'str'
    }

    attribute_map = {
        'name': 'name',
        'version': 'version',
        'driver_name': 'driver_name',
        'driver_version': 'driver_version'
    }

    def __init__(self, name=None, version=None, driver_name=None, driver_version=None):  # noqa: E501
        """CreateJdbcCatalogDetails - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._version = None
        self._driver_name = None
        self._driver_version = None
        self.discriminator = None
        self.name = name
        self.version = version
        self.driver_name = driver_name
        self.driver_version = driver_version

    @property
    def name(self):
        """Gets the name of this CreateJdbcCatalogDetails.  # noqa: E501

        The JDBC engine name  # noqa: E501

        :return: The name of this CreateJdbcCatalogDetails.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateJdbcCatalogDetails.

        The JDBC engine name  # noqa: E501

        :param name: The name of this CreateJdbcCatalogDetails.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def version(self):
        """Gets the version of this CreateJdbcCatalogDetails.  # noqa: E501

        The JDBC engine version  # noqa: E501

        :return: The version of this CreateJdbcCatalogDetails.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this CreateJdbcCatalogDetails.

        The JDBC engine version  # noqa: E501

        :param version: The version of this CreateJdbcCatalogDetails.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def driver_name(self):
        """Gets the driver_name of this CreateJdbcCatalogDetails.  # noqa: E501

        The JDBC driver name  # noqa: E501

        :return: The driver_name of this CreateJdbcCatalogDetails.  # noqa: E501
        :rtype: str
        """
        return self._driver_name

    @driver_name.setter
    def driver_name(self, driver_name):
        """Sets the driver_name of this CreateJdbcCatalogDetails.

        The JDBC driver name  # noqa: E501

        :param driver_name: The driver_name of this CreateJdbcCatalogDetails.  # noqa: E501
        :type: str
        """
        if driver_name is None:
            raise ValueError("Invalid value for `driver_name`, must not be `None`")  # noqa: E501

        self._driver_name = driver_name

    @property
    def driver_version(self):
        """Gets the driver_version of this CreateJdbcCatalogDetails.  # noqa: E501

        The JDBC driver version  # noqa: E501

        :return: The driver_version of this CreateJdbcCatalogDetails.  # noqa: E501
        :rtype: str
        """
        return self._driver_version

    @driver_version.setter
    def driver_version(self, driver_version):
        """Sets the driver_version of this CreateJdbcCatalogDetails.

        The JDBC driver version  # noqa: E501

        :param driver_version: The driver_version of this CreateJdbcCatalogDetails.  # noqa: E501
        :type: str
        """
        if driver_version is None:
            raise ValueError("Invalid value for `driver_version`, must not be `None`")  # noqa: E501

        self._driver_version = driver_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateJdbcCatalogDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateJdbcCatalogDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
