# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.create_anomaly import CreateAnomaly
from openapi_client.models.create_check_measurements import CreateCheckMeasurements
from openapi_client.models.create_check_metrics import CreateCheckMetrics
from openapi_client.models.create_partition import CreatePartition
from openapi_client.models.enrichment_source_record import EnrichmentSourceRecord
from typing import Optional, Set
from typing_extensions import Self

class CreatePartitionScan(BaseModel):
    """
    CreatePartitionScan
    """ # noqa: E501
    operation_id: StrictInt
    datastore_id: Optional[StrictInt] = None
    container_id: StrictInt
    partition: CreatePartition
    records_processed: StrictInt
    scan_start_time: datetime
    start_time: datetime
    end_time: datetime
    result: StrictStr
    message: Optional[StrictStr] = None
    anomalies: Optional[List[CreateAnomaly]] = None
    check_measurements: Optional[List[CreateCheckMeasurements]] = None
    check_metrics: Optional[List[CreateCheckMetrics]] = None
    inband_source_records: Optional[List[EnrichmentSourceRecord]] = None
    __properties: ClassVar[List[str]] = ["operation_id", "datastore_id", "container_id", "partition", "records_processed", "scan_start_time", "start_time", "end_time", "result", "message", "anomalies", "check_measurements", "check_metrics", "inband_source_records"]

    @field_validator('result')
    def result_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'failure', 'aborted']):
            raise ValueError("must be one of enum values ('success', 'failure', 'aborted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePartitionScan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of partition
        if self.partition:
            _dict['partition'] = self.partition.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in anomalies (list)
        _items = []
        if self.anomalies:
            for _item_anomalies in self.anomalies:
                if _item_anomalies:
                    _items.append(_item_anomalies.to_dict())
            _dict['anomalies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in check_measurements (list)
        _items = []
        if self.check_measurements:
            for _item_check_measurements in self.check_measurements:
                if _item_check_measurements:
                    _items.append(_item_check_measurements.to_dict())
            _dict['check_measurements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in check_metrics (list)
        _items = []
        if self.check_metrics:
            for _item_check_metrics in self.check_metrics:
                if _item_check_metrics:
                    _items.append(_item_check_metrics.to_dict())
            _dict['check_metrics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in inband_source_records (list)
        _items = []
        if self.inband_source_records:
            for _item_inband_source_records in self.inband_source_records:
                if _item_inband_source_records:
                    _items.append(_item_inband_source_records.to_dict())
            _dict['inband_source_records'] = _items
        # set to None if datastore_id (nullable) is None
        # and model_fields_set contains the field
        if self.datastore_id is None and "datastore_id" in self.model_fields_set:
            _dict['datastore_id'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if anomalies (nullable) is None
        # and model_fields_set contains the field
        if self.anomalies is None and "anomalies" in self.model_fields_set:
            _dict['anomalies'] = None

        # set to None if check_measurements (nullable) is None
        # and model_fields_set contains the field
        if self.check_measurements is None and "check_measurements" in self.model_fields_set:
            _dict['check_measurements'] = None

        # set to None if check_metrics (nullable) is None
        # and model_fields_set contains the field
        if self.check_metrics is None and "check_metrics" in self.model_fields_set:
            _dict['check_metrics'] = None

        # set to None if inband_source_records (nullable) is None
        # and model_fields_set contains the field
        if self.inband_source_records is None and "inband_source_records" in self.model_fields_set:
            _dict['inband_source_records'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePartitionScan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation_id": obj.get("operation_id"),
            "datastore_id": obj.get("datastore_id"),
            "container_id": obj.get("container_id"),
            "partition": CreatePartition.from_dict(obj["partition"]) if obj.get("partition") is not None else None,
            "records_processed": obj.get("records_processed"),
            "scan_start_time": obj.get("scan_start_time"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "result": obj.get("result"),
            "message": obj.get("message"),
            "anomalies": [CreateAnomaly.from_dict(_item) for _item in obj["anomalies"]] if obj.get("anomalies") is not None else None,
            "check_measurements": [CreateCheckMeasurements.from_dict(_item) for _item in obj["check_measurements"]] if obj.get("check_measurements") is not None else None,
            "check_metrics": [CreateCheckMetrics.from_dict(_item) for _item in obj["check_metrics"]] if obj.get("check_metrics") is not None else None,
            "inband_source_records": [EnrichmentSourceRecord.from_dict(_item) for _item in obj["inband_source_records"]] if obj.get("inband_source_records") is not None else None
        })
        return _obj


