# coding: utf-8

"""
    Surveillance Hub

    Qualytics API  # noqa: E501

    OpenAPI spec version: 5ca80d8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateJdbcCatalog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation_id': 'int',
        'details': 'CreateJdbcCatalogDetails',
        'tables': 'list[CreateTableContainer]'
    }

    attribute_map = {
        'operation_id': 'operation_id',
        'details': 'details',
        'tables': 'tables'
    }

    def __init__(self, operation_id=None, details=None, tables=None):  # noqa: E501
        """CreateJdbcCatalog - a model defined in Swagger"""  # noqa: E501
        self._operation_id = None
        self._details = None
        self._tables = None
        self.discriminator = None
        self.operation_id = operation_id
        self.details = details
        self.tables = tables

    @property
    def operation_id(self):
        """Gets the operation_id of this CreateJdbcCatalog.  # noqa: E501

        The catalog operation `Id`  # noqa: E501

        :return: The operation_id of this CreateJdbcCatalog.  # noqa: E501
        :rtype: int
        """
        return self._operation_id

    @operation_id.setter
    def operation_id(self, operation_id):
        """Sets the operation_id of this CreateJdbcCatalog.

        The catalog operation `Id`  # noqa: E501

        :param operation_id: The operation_id of this CreateJdbcCatalog.  # noqa: E501
        :type: int
        """
        if operation_id is None:
            raise ValueError("Invalid value for `operation_id`, must not be `None`")  # noqa: E501

        self._operation_id = operation_id

    @property
    def details(self):
        """Gets the details of this CreateJdbcCatalog.  # noqa: E501


        :return: The details of this CreateJdbcCatalog.  # noqa: E501
        :rtype: CreateJdbcCatalogDetails
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this CreateJdbcCatalog.


        :param details: The details of this CreateJdbcCatalog.  # noqa: E501
        :type: CreateJdbcCatalogDetails
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details

    @property
    def tables(self):
        """Gets the tables of this CreateJdbcCatalog.  # noqa: E501


        :return: The tables of this CreateJdbcCatalog.  # noqa: E501
        :rtype: list[CreateTableContainer]
        """
        return self._tables

    @tables.setter
    def tables(self, tables):
        """Sets the tables of this CreateJdbcCatalog.


        :param tables: The tables of this CreateJdbcCatalog.  # noqa: E501
        :type: list[CreateTableContainer]
        """
        if tables is None:
            raise ValueError("Invalid value for `tables`, must not be `None`")  # noqa: E501

        self._tables = tables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateJdbcCatalog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateJdbcCatalog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
