# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateScheduleActionMaterializeOperation(BaseModel):
    """
    CreateScheduleActionMaterializeOperation
    """ # noqa: E501
    trigger_type: Optional[StrictStr] = 'action'
    name: Optional[StrictStr] = None
    type: StrictStr
    container_names: Optional[List[StrictStr]] = None
    container_tags: Optional[List[StrictStr]] = None
    max_records_per_partition: Optional[StrictInt] = None
    datastore_id: StrictInt = Field(description="The datastore id of the materialize operation")
    __properties: ClassVar[List[str]] = ["trigger_type", "name", "type", "container_names", "container_tags", "max_records_per_partition", "datastore_id"]

    @field_validator('trigger_type')
    def trigger_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['action']):
            raise ValueError("must be one of enum values ('action')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['materialize']):
            raise ValueError("must be one of enum values ('materialize')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateScheduleActionMaterializeOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if container_names (nullable) is None
        # and model_fields_set contains the field
        if self.container_names is None and "container_names" in self.model_fields_set:
            _dict['container_names'] = None

        # set to None if container_tags (nullable) is None
        # and model_fields_set contains the field
        if self.container_tags is None and "container_tags" in self.model_fields_set:
            _dict['container_tags'] = None

        # set to None if max_records_per_partition (nullable) is None
        # and model_fields_set contains the field
        if self.max_records_per_partition is None and "max_records_per_partition" in self.model_fields_set:
            _dict['max_records_per_partition'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateScheduleActionMaterializeOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trigger_type": obj.get("trigger_type") if obj.get("trigger_type") is not None else 'action',
            "name": obj.get("name"),
            "type": obj.get("type"),
            "container_names": obj.get("container_names"),
            "container_tags": obj.get("container_tags"),
            "max_records_per_partition": obj.get("max_records_per_partition"),
            "datastore_id": obj.get("datastore_id")
        })
        return _obj


