# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.datastore_stub_lite import DatastoreStubLite
from typing import Optional, Set
from typing_extensions import Self

class FileContainerListing(BaseModel):
    """
    FileContainerListing
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    container_type: StrictStr
    deleted_at: Optional[datetime] = None
    volumetric_tracking_enabled: StrictBool
    freshness_tracking_enabled: StrictBool
    datastore: DatastoreStubLite
    favorite: Optional[StrictBool] = None
    was_profiled: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "container_type", "deleted_at", "volumetric_tracking_enabled", "freshness_tracking_enabled", "datastore", "favorite", "was_profiled"]

    @field_validator('container_type')
    def container_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['file']):
            raise ValueError("must be one of enum values ('file')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileContainerListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of datastore
        if self.datastore:
            _dict['datastore'] = self.datastore.to_dict()
        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        # set to None if favorite (nullable) is None
        # and model_fields_set contains the field
        if self.favorite is None and "favorite" in self.model_fields_set:
            _dict['favorite'] = None

        # set to None if was_profiled (nullable) is None
        # and model_fields_set contains the field
        if self.was_profiled is None and "was_profiled" in self.model_fields_set:
            _dict['was_profiled'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileContainerListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "container_type": obj.get("container_type"),
            "deleted_at": obj.get("deleted_at"),
            "volumetric_tracking_enabled": obj.get("volumetric_tracking_enabled"),
            "freshness_tracking_enabled": obj.get("freshness_tracking_enabled"),
            "datastore": DatastoreStubLite.from_dict(obj["datastore"]) if obj.get("datastore") is not None else None,
            "favorite": obj.get("favorite"),
            "was_profiled": obj.get("was_profiled")
        })
        return _obj


