# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.computed_file_container_global_tags_inner import ComputedFileContainerGlobalTagsInner
from openapi_client.models.datastore_stub_lite import DatastoreStubLite
from openapi_client.models.flow_actions_inner import FlowActionsInner
from openapi_client.models.rule_type import RuleType
from openapi_client.models.team import Team
from openapi_client.models.trigger_type import TriggerType
from typing import Optional, Set
from typing_extensions import Self

class Flow(BaseModel):
    """
    Flow
    """ # noqa: E501
    created: datetime
    id: StrictInt
    name: StrictStr
    description: Optional[StrictStr] = None
    deactivated: Optional[StrictBool] = None
    trigger_type: TriggerType
    filter_datastores: Optional[List[DatastoreStubLite]] = None
    filter_operation_type: Optional[List[StrictStr]] = None
    filter_operation_result: Optional[StrictStr] = None
    actions: Optional[List[FlowActionsInner]] = None
    teams: Optional[List[Team]] = None
    global_tags: Optional[List[ComputedFileContainerGlobalTagsInner]] = None
    weight_threshold: Optional[StrictInt] = None
    check_rule_types: Optional[List[RuleType]] = None
    last_triggered: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["created", "id", "name", "description", "deactivated", "trigger_type", "filter_datastores", "filter_operation_type", "filter_operation_result", "actions", "teams", "global_tags", "weight_threshold", "check_rule_types", "last_triggered"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Flow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filter_datastores (list)
        _items = []
        if self.filter_datastores:
            for _item_filter_datastores in self.filter_datastores:
                if _item_filter_datastores:
                    _items.append(_item_filter_datastores.to_dict())
            _dict['filter_datastores'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in teams (list)
        _items = []
        if self.teams:
            for _item_teams in self.teams:
                if _item_teams:
                    _items.append(_item_teams.to_dict())
            _dict['teams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in global_tags (list)
        _items = []
        if self.global_tags:
            for _item_global_tags in self.global_tags:
                if _item_global_tags:
                    _items.append(_item_global_tags.to_dict())
            _dict['global_tags'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if deactivated (nullable) is None
        # and model_fields_set contains the field
        if self.deactivated is None and "deactivated" in self.model_fields_set:
            _dict['deactivated'] = None

        # set to None if filter_datastores (nullable) is None
        # and model_fields_set contains the field
        if self.filter_datastores is None and "filter_datastores" in self.model_fields_set:
            _dict['filter_datastores'] = None

        # set to None if filter_operation_type (nullable) is None
        # and model_fields_set contains the field
        if self.filter_operation_type is None and "filter_operation_type" in self.model_fields_set:
            _dict['filter_operation_type'] = None

        # set to None if filter_operation_result (nullable) is None
        # and model_fields_set contains the field
        if self.filter_operation_result is None and "filter_operation_result" in self.model_fields_set:
            _dict['filter_operation_result'] = None

        # set to None if actions (nullable) is None
        # and model_fields_set contains the field
        if self.actions is None and "actions" in self.model_fields_set:
            _dict['actions'] = None

        # set to None if teams (nullable) is None
        # and model_fields_set contains the field
        if self.teams is None and "teams" in self.model_fields_set:
            _dict['teams'] = None

        # set to None if global_tags (nullable) is None
        # and model_fields_set contains the field
        if self.global_tags is None and "global_tags" in self.model_fields_set:
            _dict['global_tags'] = None

        # set to None if weight_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.weight_threshold is None and "weight_threshold" in self.model_fields_set:
            _dict['weight_threshold'] = None

        # set to None if check_rule_types (nullable) is None
        # and model_fields_set contains the field
        if self.check_rule_types is None and "check_rule_types" in self.model_fields_set:
            _dict['check_rule_types'] = None

        # set to None if last_triggered (nullable) is None
        # and model_fields_set contains the field
        if self.last_triggered is None and "last_triggered" in self.model_fields_set:
            _dict['last_triggered'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Flow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "deactivated": obj.get("deactivated"),
            "trigger_type": obj.get("trigger_type"),
            "filter_datastores": [DatastoreStubLite.from_dict(_item) for _item in obj["filter_datastores"]] if obj.get("filter_datastores") is not None else None,
            "filter_operation_type": obj.get("filter_operation_type"),
            "filter_operation_result": obj.get("filter_operation_result"),
            "actions": [FlowActionsInner.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "teams": [Team.from_dict(_item) for _item in obj["teams"]] if obj.get("teams") is not None else None,
            "global_tags": [ComputedFileContainerGlobalTagsInner.from_dict(_item) for _item in obj["global_tags"]] if obj.get("global_tags") is not None else None,
            "weight_threshold": obj.get("weight_threshold"),
            "check_rule_types": obj.get("check_rule_types"),
            "last_triggered": obj.get("last_triggered")
        })
        return _obj


