# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from swagger_client.models.computed_file_container_global_tags_inner import ComputedFileContainerGlobalTagsInner
from typing import Optional, Set
from typing_extensions import Self

class FlowStubPermission(BaseModel):
    """
    FlowStubPermission
    """ # noqa: E501
    created: datetime
    id: StrictInt
    name: StrictStr
    description: Optional[StrictStr] = None
    deactivated: Optional[StrictBool] = None
    global_tags: Optional[List[ComputedFileContainerGlobalTagsInner]] = None
    user_can_manage: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["created", "id", "name", "description", "deactivated", "global_tags", "user_can_manage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FlowStubPermission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in global_tags (list)
        _items = []
        if self.global_tags:
            for _item_global_tags in self.global_tags:
                if _item_global_tags:
                    _items.append(_item_global_tags.to_dict())
            _dict['global_tags'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if deactivated (nullable) is None
        # and model_fields_set contains the field
        if self.deactivated is None and "deactivated" in self.model_fields_set:
            _dict['deactivated'] = None

        # set to None if global_tags (nullable) is None
        # and model_fields_set contains the field
        if self.global_tags is None and "global_tags" in self.model_fields_set:
            _dict['global_tags'] = None

        # set to None if user_can_manage (nullable) is None
        # and model_fields_set contains the field
        if self.user_can_manage is None and "user_can_manage" in self.model_fields_set:
            _dict['user_can_manage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FlowStubPermission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "deactivated": obj.get("deactivated"),
            "global_tags": [ComputedFileContainerGlobalTagsInner.from_dict(_item) for _item in obj["global_tags"]] if obj.get("global_tags") is not None else None,
            "user_can_manage": obj.get("user_can_manage")
        })
        return _obj


