# coding: utf-8

"""
    Surveillance Hub

    Qualytics API  # noqa: E501

    OpenAPI spec version: 5ca80d8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FreshnessMeasurement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'created': 'datetime',
        'measurement_time': 'datetime',
        'last_modification_time': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'measurement_time': 'measurement_time',
        'last_modification_time': 'last_modification_time'
    }

    def __init__(self, id=None, created=None, measurement_time=None, last_modification_time=None):  # noqa: E501
        """FreshnessMeasurement - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created = None
        self._measurement_time = None
        self._last_modification_time = None
        self.discriminator = None
        self.id = id
        self.created = created
        self.measurement_time = measurement_time
        self.last_modification_time = last_modification_time

    @property
    def id(self):
        """Gets the id of this FreshnessMeasurement.  # noqa: E501


        :return: The id of this FreshnessMeasurement.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FreshnessMeasurement.


        :param id: The id of this FreshnessMeasurement.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created(self):
        """Gets the created of this FreshnessMeasurement.  # noqa: E501


        :return: The created of this FreshnessMeasurement.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this FreshnessMeasurement.


        :param created: The created of this FreshnessMeasurement.  # noqa: E501
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def measurement_time(self):
        """Gets the measurement_time of this FreshnessMeasurement.  # noqa: E501


        :return: The measurement_time of this FreshnessMeasurement.  # noqa: E501
        :rtype: datetime
        """
        return self._measurement_time

    @measurement_time.setter
    def measurement_time(self, measurement_time):
        """Sets the measurement_time of this FreshnessMeasurement.


        :param measurement_time: The measurement_time of this FreshnessMeasurement.  # noqa: E501
        :type: datetime
        """
        if measurement_time is None:
            raise ValueError("Invalid value for `measurement_time`, must not be `None`")  # noqa: E501

        self._measurement_time = measurement_time

    @property
    def last_modification_time(self):
        """Gets the last_modification_time of this FreshnessMeasurement.  # noqa: E501


        :return: The last_modification_time of this FreshnessMeasurement.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modification_time

    @last_modification_time.setter
    def last_modification_time(self, last_modification_time):
        """Sets the last_modification_time of this FreshnessMeasurement.


        :param last_modification_time: The last_modification_time of this FreshnessMeasurement.  # noqa: E501
        :type: datetime
        """
        if last_modification_time is None:
            raise ValueError("Invalid value for `last_modification_time`, must not be `None`")  # noqa: E501

        self._last_modification_time = last_modification_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FreshnessMeasurement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FreshnessMeasurement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
