# coding: utf-8

"""
    Surveillance Hub

    Qualytics API  # noqa: E501

    OpenAPI spec version: 5ca80d8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FreshnessSla(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'created': 'datetime',
        'first_starting_time': 'datetime',
        'next_violation_time': 'datetime',
        'current_window_start_time': 'datetime',
        'repeating_duration': 'int',
        'duration_units': 'str'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'first_starting_time': 'first_starting_time',
        'next_violation_time': 'next_violation_time',
        'current_window_start_time': 'current_window_start_time',
        'repeating_duration': 'repeating_duration',
        'duration_units': 'duration_units'
    }

    def __init__(self, id=None, created=None, first_starting_time=None, next_violation_time=None, current_window_start_time=None, repeating_duration=None, duration_units=None):  # noqa: E501
        """FreshnessSla - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created = None
        self._first_starting_time = None
        self._next_violation_time = None
        self._current_window_start_time = None
        self._repeating_duration = None
        self._duration_units = None
        self.discriminator = None
        self.id = id
        self.created = created
        self.first_starting_time = first_starting_time
        self.next_violation_time = next_violation_time
        self.current_window_start_time = current_window_start_time
        self.repeating_duration = repeating_duration
        self.duration_units = duration_units

    @property
    def id(self):
        """Gets the id of this FreshnessSla.  # noqa: E501


        :return: The id of this FreshnessSla.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FreshnessSla.


        :param id: The id of this FreshnessSla.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created(self):
        """Gets the created of this FreshnessSla.  # noqa: E501


        :return: The created of this FreshnessSla.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this FreshnessSla.


        :param created: The created of this FreshnessSla.  # noqa: E501
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def first_starting_time(self):
        """Gets the first_starting_time of this FreshnessSla.  # noqa: E501


        :return: The first_starting_time of this FreshnessSla.  # noqa: E501
        :rtype: datetime
        """
        return self._first_starting_time

    @first_starting_time.setter
    def first_starting_time(self, first_starting_time):
        """Sets the first_starting_time of this FreshnessSla.


        :param first_starting_time: The first_starting_time of this FreshnessSla.  # noqa: E501
        :type: datetime
        """
        if first_starting_time is None:
            raise ValueError("Invalid value for `first_starting_time`, must not be `None`")  # noqa: E501

        self._first_starting_time = first_starting_time

    @property
    def next_violation_time(self):
        """Gets the next_violation_time of this FreshnessSla.  # noqa: E501


        :return: The next_violation_time of this FreshnessSla.  # noqa: E501
        :rtype: datetime
        """
        return self._next_violation_time

    @next_violation_time.setter
    def next_violation_time(self, next_violation_time):
        """Sets the next_violation_time of this FreshnessSla.


        :param next_violation_time: The next_violation_time of this FreshnessSla.  # noqa: E501
        :type: datetime
        """
        if next_violation_time is None:
            raise ValueError("Invalid value for `next_violation_time`, must not be `None`")  # noqa: E501

        self._next_violation_time = next_violation_time

    @property
    def current_window_start_time(self):
        """Gets the current_window_start_time of this FreshnessSla.  # noqa: E501


        :return: The current_window_start_time of this FreshnessSla.  # noqa: E501
        :rtype: datetime
        """
        return self._current_window_start_time

    @current_window_start_time.setter
    def current_window_start_time(self, current_window_start_time):
        """Sets the current_window_start_time of this FreshnessSla.


        :param current_window_start_time: The current_window_start_time of this FreshnessSla.  # noqa: E501
        :type: datetime
        """
        if current_window_start_time is None:
            raise ValueError("Invalid value for `current_window_start_time`, must not be `None`")  # noqa: E501

        self._current_window_start_time = current_window_start_time

    @property
    def repeating_duration(self):
        """Gets the repeating_duration of this FreshnessSla.  # noqa: E501


        :return: The repeating_duration of this FreshnessSla.  # noqa: E501
        :rtype: int
        """
        return self._repeating_duration

    @repeating_duration.setter
    def repeating_duration(self, repeating_duration):
        """Sets the repeating_duration of this FreshnessSla.


        :param repeating_duration: The repeating_duration of this FreshnessSla.  # noqa: E501
        :type: int
        """
        if repeating_duration is None:
            raise ValueError("Invalid value for `repeating_duration`, must not be `None`")  # noqa: E501

        self._repeating_duration = repeating_duration

    @property
    def duration_units(self):
        """Gets the duration_units of this FreshnessSla.  # noqa: E501


        :return: The duration_units of this FreshnessSla.  # noqa: E501
        :rtype: str
        """
        return self._duration_units

    @duration_units.setter
    def duration_units(self, duration_units):
        """Sets the duration_units of this FreshnessSla.


        :param duration_units: The duration_units of this FreshnessSla.  # noqa: E501
        :type: str
        """
        if duration_units is None:
            raise ValueError("Invalid value for `duration_units`, must not be `None`")  # noqa: E501
        allowed_values = ["minutes", "hours", "days", "months"]  # noqa: E501
        if duration_units not in allowed_values:
            raise ValueError(
                "Invalid value for `duration_units` ({0}), must be one of {1}"  # noqa: E501
                .format(duration_units, allowed_values)
            )

        self._duration_units = duration_units

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FreshnessSla, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FreshnessSla):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
