# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from openapi_client.models.get_assertion_daily_metric import GetAssertionDailyMetric
from openapi_client.models.insights_timeframe import InsightsTimeframe
from typing import Optional, Set
from typing_extensions import Self

class GetQualityCheckInsights(BaseModel):
    """
    GetQualityCheckInsights
    """ # noqa: E501
    generated_at: datetime
    start_date: date
    end_date: date
    timeframe: InsightsTimeframe
    daily_assertion_measured: List[GetAssertionDailyMetric]
    __properties: ClassVar[List[str]] = ["generated_at", "start_date", "end_date", "timeframe", "daily_assertion_measured"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetQualityCheckInsights from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in daily_assertion_measured (list)
        _items = []
        if self.daily_assertion_measured:
            for _item_daily_assertion_measured in self.daily_assertion_measured:
                if _item_daily_assertion_measured:
                    _items.append(_item_daily_assertion_measured.to_dict())
            _dict['daily_assertion_measured'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetQualityCheckInsights from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "generated_at": obj.get("generated_at"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "timeframe": obj.get("timeframe"),
            "daily_assertion_measured": [GetAssertionDailyMetric.from_dict(_item) for _item in obj["daily_assertion_measured"]] if obj.get("daily_assertion_measured") is not None else None
        })
        return _obj


