# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetConnectionSecretsManager(BaseModel):
    """
    GetConnectionSecretsManager
    """ # noqa: E501
    login_url: Optional[StrictStr] = Field(default=None, description="The URL where the credentials payload will be POST'ed to retrieve a token")
    token_jsonpath: Optional[StrictStr] = Field(default='$.auth.client_token', description="The jsonpath to retrieve the authorized token from the login response")
    secret_url: StrictStr = Field(description="The URL where the secret will be retrieved with a GET")
    token_header_name: Optional[StrictStr] = Field(default='X-Vault-Token', description="The name of the header that will be used to pass the token retrieved during authentication")
    data_jsonpath: Optional[StrictStr] = Field(default='$.data', description="The jsonpath to retrieve the key-value data from the secret URL response")
    __properties: ClassVar[List[str]] = ["login_url", "token_jsonpath", "secret_url", "token_header_name", "data_jsonpath"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetConnectionSecretsManager from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetConnectionSecretsManager from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "login_url": obj.get("login_url"),
            "token_jsonpath": obj.get("token_jsonpath") if obj.get("token_jsonpath") is not None else '$.auth.client_token',
            "secret_url": obj.get("secret_url"),
            "token_header_name": obj.get("token_header_name") if obj.get("token_header_name") is not None else 'X-Vault-Token',
            "data_jsonpath": obj.get("data_jsonpath") if obj.get("data_jsonpath") is not None else '$.data'
        })
        return _obj


