# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.get_operation_computed_file_container import GetOperationComputedFileContainer
from openapi_client.models.get_operation_computed_join_container import GetOperationComputedJoinContainer
from openapi_client.models.get_operation_computed_table_container import GetOperationComputedTableContainer
from openapi_client.models.get_operation_file_container import GetOperationFileContainer
from openapi_client.models.get_operation_table_container import GetOperationTableContainer
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

PAGEUNIONGETOPERATIONTABLECONTAINERGETOPERATIONFILECONTAINERGETOPERATIONCOMPUTEDTABLECONTAINERGETOPERATIONCOMPUTEDFILECONTAINERGETOPERATIONCOMPUTEDJOINCONTAINERITEMSINNER_ANY_OF_SCHEMAS = ["GetOperationComputedFileContainer", "GetOperationComputedJoinContainer", "GetOperationComputedTableContainer", "GetOperationFileContainer", "GetOperationTableContainer"]

class PageUnionGetOperationTableContainerGetOperationFileContainerGetOperationComputedTableContainerGetOperationComputedFileContainerGetOperationComputedJoinContainerItemsInner(BaseModel):
    """
    PageUnionGetOperationTableContainerGetOperationFileContainerGetOperationComputedTableContainerGetOperationComputedFileContainerGetOperationComputedJoinContainerItemsInner
    """

    # data type: GetOperationTableContainer
    anyof_schema_1_validator: Optional[GetOperationTableContainer] = None
    # data type: GetOperationFileContainer
    anyof_schema_2_validator: Optional[GetOperationFileContainer] = None
    # data type: GetOperationComputedTableContainer
    anyof_schema_3_validator: Optional[GetOperationComputedTableContainer] = None
    # data type: GetOperationComputedFileContainer
    anyof_schema_4_validator: Optional[GetOperationComputedFileContainer] = None
    # data type: GetOperationComputedJoinContainer
    anyof_schema_5_validator: Optional[GetOperationComputedJoinContainer] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[GetOperationComputedFileContainer, GetOperationComputedJoinContainer, GetOperationComputedTableContainer, GetOperationFileContainer, GetOperationTableContainer]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "GetOperationComputedFileContainer", "GetOperationComputedJoinContainer", "GetOperationComputedTableContainer", "GetOperationFileContainer", "GetOperationTableContainer" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = PageUnionGetOperationTableContainerGetOperationFileContainerGetOperationComputedTableContainerGetOperationComputedFileContainerGetOperationComputedJoinContainerItemsInner.model_construct()
        error_messages = []
        # validate data type: GetOperationTableContainer
        if not isinstance(v, GetOperationTableContainer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetOperationTableContainer`")
        else:
            return v

        # validate data type: GetOperationFileContainer
        if not isinstance(v, GetOperationFileContainer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetOperationFileContainer`")
        else:
            return v

        # validate data type: GetOperationComputedTableContainer
        if not isinstance(v, GetOperationComputedTableContainer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetOperationComputedTableContainer`")
        else:
            return v

        # validate data type: GetOperationComputedFileContainer
        if not isinstance(v, GetOperationComputedFileContainer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetOperationComputedFileContainer`")
        else:
            return v

        # validate data type: GetOperationComputedJoinContainer
        if not isinstance(v, GetOperationComputedJoinContainer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetOperationComputedJoinContainer`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in PageUnionGetOperationTableContainerGetOperationFileContainerGetOperationComputedTableContainerGetOperationComputedFileContainerGetOperationComputedJoinContainerItemsInner with anyOf schemas: GetOperationComputedFileContainer, GetOperationComputedJoinContainer, GetOperationComputedTableContainer, GetOperationFileContainer, GetOperationTableContainer. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[GetOperationTableContainer] = None
        try:
            instance.actual_instance = GetOperationTableContainer.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[GetOperationFileContainer] = None
        try:
            instance.actual_instance = GetOperationFileContainer.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[GetOperationComputedTableContainer] = None
        try:
            instance.actual_instance = GetOperationComputedTableContainer.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[GetOperationComputedFileContainer] = None
        try:
            instance.actual_instance = GetOperationComputedFileContainer.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[GetOperationComputedJoinContainer] = None
        try:
            instance.actual_instance = GetOperationComputedJoinContainer.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PageUnionGetOperationTableContainerGetOperationFileContainerGetOperationComputedTableContainerGetOperationComputedFileContainerGetOperationComputedJoinContainerItemsInner with anyOf schemas: GetOperationComputedFileContainer, GetOperationComputedJoinContainer, GetOperationComputedTableContainer, GetOperationFileContainer, GetOperationTableContainer. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GetOperationComputedFileContainer, GetOperationComputedJoinContainer, GetOperationComputedTableContainer, GetOperationFileContainer, GetOperationTableContainer]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


