# coding: utf-8

"""
    Surveillance Hub

    Qualytics API  # noqa: E501

    OpenAPI spec version: 5ca80d8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RegressionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'created': 'datetime',
        'intercept': 'float',
        'r2': 'float',
        'root_mean_squared_error': 'float',
        'features': 'list[ModelFeature]'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'intercept': 'intercept',
        'r2': 'r2',
        'root_mean_squared_error': 'root_mean_squared_error',
        'features': 'features'
    }

    def __init__(self, id=None, created=None, intercept=None, r2=None, root_mean_squared_error=None, features=None):  # noqa: E501
        """RegressionModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created = None
        self._intercept = None
        self._r2 = None
        self._root_mean_squared_error = None
        self._features = None
        self.discriminator = None
        self.id = id
        self.created = created
        self.intercept = intercept
        self.r2 = r2
        self.root_mean_squared_error = root_mean_squared_error
        self.features = features

    @property
    def id(self):
        """Gets the id of this RegressionModel.  # noqa: E501


        :return: The id of this RegressionModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RegressionModel.


        :param id: The id of this RegressionModel.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created(self):
        """Gets the created of this RegressionModel.  # noqa: E501


        :return: The created of this RegressionModel.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this RegressionModel.


        :param created: The created of this RegressionModel.  # noqa: E501
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def intercept(self):
        """Gets the intercept of this RegressionModel.  # noqa: E501


        :return: The intercept of this RegressionModel.  # noqa: E501
        :rtype: float
        """
        return self._intercept

    @intercept.setter
    def intercept(self, intercept):
        """Sets the intercept of this RegressionModel.


        :param intercept: The intercept of this RegressionModel.  # noqa: E501
        :type: float
        """
        if intercept is None:
            raise ValueError("Invalid value for `intercept`, must not be `None`")  # noqa: E501

        self._intercept = intercept

    @property
    def r2(self):
        """Gets the r2 of this RegressionModel.  # noqa: E501


        :return: The r2 of this RegressionModel.  # noqa: E501
        :rtype: float
        """
        return self._r2

    @r2.setter
    def r2(self, r2):
        """Sets the r2 of this RegressionModel.


        :param r2: The r2 of this RegressionModel.  # noqa: E501
        :type: float
        """
        if r2 is None:
            raise ValueError("Invalid value for `r2`, must not be `None`")  # noqa: E501

        self._r2 = r2

    @property
    def root_mean_squared_error(self):
        """Gets the root_mean_squared_error of this RegressionModel.  # noqa: E501


        :return: The root_mean_squared_error of this RegressionModel.  # noqa: E501
        :rtype: float
        """
        return self._root_mean_squared_error

    @root_mean_squared_error.setter
    def root_mean_squared_error(self, root_mean_squared_error):
        """Sets the root_mean_squared_error of this RegressionModel.


        :param root_mean_squared_error: The root_mean_squared_error of this RegressionModel.  # noqa: E501
        :type: float
        """
        if root_mean_squared_error is None:
            raise ValueError("Invalid value for `root_mean_squared_error`, must not be `None`")  # noqa: E501

        self._root_mean_squared_error = root_mean_squared_error

    @property
    def features(self):
        """Gets the features of this RegressionModel.  # noqa: E501


        :return: The features of this RegressionModel.  # noqa: E501
        :rtype: list[ModelFeature]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this RegressionModel.


        :param features: The features of this RegressionModel.  # noqa: E501
        :type: list[ModelFeature]
        """
        if features is None:
            raise ValueError("Invalid value for `features`, must not be `None`")  # noqa: E501

        self._features = features

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegressionModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegressionModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
