# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from swagger_client.models.get_entity_tag import GetEntityTag
from swagger_client.models.get_external_tag import GetExternalTag
from swagger_client.models.get_global_tag import GetGlobalTag
from swagger_client.models.get_lineage_tag import GetLineageTag
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

RESPONSEUPDATEGLOBALTAGAPIGLOBALTAGSNAMEPUT_ONE_OF_SCHEMAS = ["GetEntityTag", "GetExternalTag", "GetGlobalTag", "GetLineageTag"]

class ResponseUpdateGlobalTagApiGlobalTagsNamePut(BaseModel):
    """
    ResponseUpdateGlobalTagApiGlobalTagsNamePut
    """
    # data type: GetGlobalTag
    oneof_schema_1_validator: Optional[GetGlobalTag] = None
    # data type: GetEntityTag
    oneof_schema_2_validator: Optional[GetEntityTag] = None
    # data type: GetLineageTag
    oneof_schema_3_validator: Optional[GetLineageTag] = None
    # data type: GetExternalTag
    oneof_schema_4_validator: Optional[GetExternalTag] = None
    actual_instance: Optional[Union[GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag]] = None
    one_of_schemas: Set[str] = { "GetEntityTag", "GetExternalTag", "GetGlobalTag", "GetLineageTag" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ResponseUpdateGlobalTagApiGlobalTagsNamePut.model_construct()
        error_messages = []
        match = 0
        # validate data type: GetGlobalTag
        if not isinstance(v, GetGlobalTag):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetGlobalTag`")
        else:
            match += 1
        # validate data type: GetEntityTag
        if not isinstance(v, GetEntityTag):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetEntityTag`")
        else:
            match += 1
        # validate data type: GetLineageTag
        if not isinstance(v, GetLineageTag):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetLineageTag`")
        else:
            match += 1
        # validate data type: GetExternalTag
        if not isinstance(v, GetExternalTag):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GetExternalTag`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ResponseUpdateGlobalTagApiGlobalTagsNamePut with oneOf schemas: GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ResponseUpdateGlobalTagApiGlobalTagsNamePut with oneOf schemas: GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GetGlobalTag
        try:
            instance.actual_instance = GetGlobalTag.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetEntityTag
        try:
            instance.actual_instance = GetEntityTag.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetLineageTag
        try:
            instance.actual_instance = GetLineageTag.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GetExternalTag
        try:
            instance.actual_instance = GetExternalTag.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ResponseUpdateGlobalTagApiGlobalTagsNamePut with oneOf schemas: GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ResponseUpdateGlobalTagApiGlobalTagsNamePut with oneOf schemas: GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GetEntityTag, GetExternalTag, GetGlobalTag, GetLineageTag]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


