# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from swagger_client.models.catalog_operation import CatalogOperation
from swagger_client.models.export_operation import ExportOperation
from swagger_client.models.materialize_operation import MaterializeOperation
from swagger_client.models.profile_operation import ProfileOperation
from swagger_client.models.scan_operation import ScanOperation
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

RESPONSERUNOPERATIONAPIOPERATIONSRUNPOST_ANY_OF_SCHEMAS = ["CatalogOperation", "ExportOperation", "MaterializeOperation", "ProfileOperation", "ScanOperation"]

class ResponseRunOperationApiOperationsRunPost(BaseModel):
    """
    ResponseRunOperationApiOperationsRunPost
    """

    # data type: CatalogOperation
    anyof_schema_1_validator: Optional[CatalogOperation] = None
    # data type: ProfileOperation
    anyof_schema_2_validator: Optional[ProfileOperation] = None
    # data type: ScanOperation
    anyof_schema_3_validator: Optional[ScanOperation] = None
    # data type: MaterializeOperation
    anyof_schema_4_validator: Optional[MaterializeOperation] = None
    # data type: ExportOperation
    anyof_schema_5_validator: Optional[ExportOperation] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CatalogOperation, ExportOperation, MaterializeOperation, ProfileOperation, ScanOperation]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CatalogOperation", "ExportOperation", "MaterializeOperation", "ProfileOperation", "ScanOperation" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        if v is None:
            return v

        instance = ResponseRunOperationApiOperationsRunPost.model_construct()
        error_messages = []
        # validate data type: CatalogOperation
        if not isinstance(v, CatalogOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CatalogOperation`")
        else:
            return v

        # validate data type: ProfileOperation
        if not isinstance(v, ProfileOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProfileOperation`")
        else:
            return v

        # validate data type: ScanOperation
        if not isinstance(v, ScanOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ScanOperation`")
        else:
            return v

        # validate data type: MaterializeOperation
        if not isinstance(v, MaterializeOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MaterializeOperation`")
        else:
            return v

        # validate data type: ExportOperation
        if not isinstance(v, ExportOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ExportOperation`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ResponseRunOperationApiOperationsRunPost with anyOf schemas: CatalogOperation, ExportOperation, MaterializeOperation, ProfileOperation, ScanOperation. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        # anyof_schema_1_validator: Optional[CatalogOperation] = None
        try:
            instance.actual_instance = CatalogOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ProfileOperation] = None
        try:
            instance.actual_instance = ProfileOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ScanOperation] = None
        try:
            instance.actual_instance = ScanOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[MaterializeOperation] = None
        try:
            instance.actual_instance = MaterializeOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ExportOperation] = None
        try:
            instance.actual_instance = ExportOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ResponseRunOperationApiOperationsRunPost with anyOf schemas: CatalogOperation, ExportOperation, MaterializeOperation, ProfileOperation, ScanOperation. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CatalogOperation, ExportOperation, MaterializeOperation, ProfileOperation, ScanOperation]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


