# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransformationType(str, Enum):
    """
    TransformationType
    """

    """
    allowed enum values
    """
    CLEANEDENTITYNAME = 'cleanedEntityName'
    CONVERTFORMATTEDNUMERIC = 'convertFormattedNumeric'
    CUSTOMEXPRESSION = 'customExpression'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransformationType from a JSON string"""
        return cls(json.loads(json_str))


