# coding: utf-8

"""
    Controlplane

    Qualytics API

    The version of the OpenAPI document: 20251024-3d1ade3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from swagger_client.models.create_action_notification import CreateActionNotification
from swagger_client.models.create_action_operation import CreateActionOperation
from swagger_client.models.update_action_notification import UpdateActionNotification
from swagger_client.models.update_action_operation import UpdateActionOperation
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

UPDATEFLOWACTIONSINNER_ANY_OF_SCHEMAS = ["CreateActionNotification", "CreateActionOperation", "UpdateActionNotification", "UpdateActionOperation"]

class UpdateFlowActionsInner(BaseModel):
    """
    UpdateFlowActionsInner
    """

    # data type: CreateActionNotification
    anyof_schema_1_validator: Optional[CreateActionNotification] = None
    # data type: CreateActionOperation
    anyof_schema_2_validator: Optional[CreateActionOperation] = None
    # data type: UpdateActionNotification
    anyof_schema_3_validator: Optional[UpdateActionNotification] = None
    # data type: UpdateActionOperation
    anyof_schema_4_validator: Optional[UpdateActionOperation] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CreateActionNotification, CreateActionOperation, UpdateActionNotification, UpdateActionOperation]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CreateActionNotification", "CreateActionOperation", "UpdateActionNotification", "UpdateActionOperation" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = UpdateFlowActionsInner.model_construct()
        error_messages = []
        # validate data type: CreateActionNotification
        if not isinstance(v, CreateActionNotification):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateActionNotification`")
        else:
            return v

        # validate data type: CreateActionOperation
        if not isinstance(v, CreateActionOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateActionOperation`")
        else:
            return v

        # validate data type: UpdateActionNotification
        if not isinstance(v, UpdateActionNotification):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UpdateActionNotification`")
        else:
            return v

        # validate data type: UpdateActionOperation
        if not isinstance(v, UpdateActionOperation):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UpdateActionOperation`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in UpdateFlowActionsInner with anyOf schemas: CreateActionNotification, CreateActionOperation, UpdateActionNotification, UpdateActionOperation. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[CreateActionNotification] = None
        try:
            instance.actual_instance = CreateActionNotification.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CreateActionOperation] = None
        try:
            instance.actual_instance = CreateActionOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[UpdateActionNotification] = None
        try:
            instance.actual_instance = UpdateActionNotification.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[UpdateActionOperation] = None
        try:
            instance.actual_instance = UpdateActionOperation.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into UpdateFlowActionsInner with anyOf schemas: CreateActionNotification, CreateActionOperation, UpdateActionNotification, UpdateActionOperation. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CreateActionNotification, CreateActionOperation, UpdateActionNotification, UpdateActionOperation]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


